package com.aladdin.plugin.docs

import com.aladdin.plugin.api.BasePlugin
import com.aladdin.plugin.model.PluginInfo
import java.io.File

/**
 * Auto-generates Markdown documentation for a plugin from its metadata.
 */
object PluginDocGenerator {

    /**
     * Generate a Markdown doc string for a single plugin.
     */
    fun generateMarkdown(info: PluginInfo): String = buildString {
        appendLine("# ${info.name}")
        appendLine()
        appendLine("> ${info.description}")
        appendLine()
        appendLine("| Field | Value |")
        appendLine("|-------|-------|")
        appendLine("| **Plugin ID** | `${info.pluginId}` |")
        appendLine("| **Version** | ${info.version} |")
        appendLine("| **Author** | ${info.author} |")
        appendLine("| **Min Aladdin Version** | ${info.minAladdinVersion} |")
        appendLine("| **Status** | ${info.state.name} |")
        if (info.tags.isNotEmpty()) appendLine("| **Tags** | ${info.tags.joinToString(", ")} |")
        appendLine()

        if (info.requiredPermissions.isNotEmpty()) {
            appendLine("## Required Permissions")
            appendLine()
            appendLine("| Permission | Description |")
            appendLine("|------------|-------------|")
            info.requiredPermissions.forEach { perm ->
                appendLine("| `${perm.name}` | ${perm.description} |")
            }
            appendLine()
        }

        if (info.handledCommands.isNotEmpty()) {
            appendLine("## Handled Commands")
            appendLine()
            info.handledCommands.forEach { cmd ->
                appendLine("- `$cmd`")
            }
            appendLine()
        }

        appendLine("## Installation")
        appendLine()
        appendLine("1. Copy `${File(info.apkPath).name}` to the Aladdin plugins directory.")
        appendLine("2. Open Aladdin → Settings → Plugin Manager.")
        appendLine("3. Tap **Discover Plugins**.")
        appendLine("4. Grant the required permissions when prompted.")
        appendLine("5. Enable the plugin.")
        appendLine()
        appendLine("---")
        appendLine("*Auto-generated by Aladdin Plugin Doc Generator*")
    }

    /**
     * Generate an index of all plugins.
     */
    fun generateIndex(plugins: List<PluginInfo>): String = buildString {
        appendLine("# Aladdin Plugin Index")
        appendLine()
        appendLine("${plugins.size} plugin(s) installed.")
        appendLine()
        appendLine("| Name | ID | Version | Author | Status |")
        appendLine("|------|----|---------|--------|--------|")
        plugins.forEach { p ->
            appendLine("| ${p.name} | `${p.pluginId}` | ${p.version} | ${p.author} | ${p.state.name} |")
        }
    }

    /**
     * Write documentation to a directory, one file per plugin.
     */
    fun writeToDirectory(plugins: List<PluginInfo>, outputDir: File) {
        outputDir.mkdirs()
        File(outputDir, "INDEX.md").writeText(generateIndex(plugins))
        plugins.forEach { info ->
            val file = File(outputDir, "${info.pluginId}.md")
            file.writeText(generateMarkdown(info))
        }
    }
}
